### PR TITLE
[WIP] Parameterized NIC

### PR DESCRIPTION
**Pull request by abejgonzalez**
These changes coincide with PR: https://github.com/firesim/firesim/pull/214

### CODE REVIEW

**Comment by abejgonzalez** [comment]
Note: I tried to add comments to as many classes as possible but some I didn't know what to put (or what it did)

**Comment by abejgonzalez** [comment]
Renamed to WIP. Explanation in https://github.com/firesim/firesim/pull/214

**Comment by zhemao** [comment]
Wait, so you didn't change the logic inside IceNicWriter, which ignores the "keep" field. You also don't change the issue that Writer won't handle misaligned writes properly.

**Comment by abejgonzalez** [comment]
On the keep question (or comment):

IceNicWriter will take the `keep` from the StreamShifter and use it to make the TL request out to memory. From the `ext` you don't get `keep` values, so I assume that you "keep" everything coming from externally into the recvpath.

On the misaligned writes:

I am currently dealing with an issue in the IceNICWriter on misaligned writes. So I am working on it.

**Comment by abejgonzalez** [comment]
This PR is now very stale. Will be updated in the summer with the proper changes.

**Pull request closed without merging**
